name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create temporary artifact folder
      run: mkdir artifacts
      
    - name: Create zip file
      run: zip -vr artifacts/optimize-images optimize-images

    - name: Upload artifacts for workflow
      uses: actions/upload-artifact@v4
      with: 
          name: artifacts
          path: artifacts

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: artifacts/optimize-images.zip
