name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create temporary artifact folder
      run: mkdir artifacts
      
    - name: Create zip file
      run: zip -o artifacts/optimize-images -r optimize-images

    - name: Upload artifacts for workflow
      uses: actions/upload-artifact@v3
      with: 
          name: artifacts
          path: artifacts

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: artifacts/optimize-images.zip
